#!/usr/bin/env bash

echo "Creating database pokefeed-api..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database pokefeed-api-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://mattkim@localhost:5432/pokefeed-api-test?sslmode=disable..."
pgmgr -c ".pgmgr.test.json" db migrate
